// =============================================================
// 🔥 HYPER VIBE CODING COURSE — STRIPE PRODUCTS & PRICES CONFIG
// Auto-generated by BROski AI — May 2026
// All prices in GBP (pence). Divide by 100 for £ value.
// =============================================================

export const STRIPE_PRODUCTS = {
  starter: {
    productId: 'prod_UWqiI5b5vIgCat',
    name: '🌱 Starter — Hyper Vibe Coding Course',
    description: 'Modules 1–4 — Focus Zone, Docker, Prompting, First App',
    prices: {
      oneTime: {
        priceId: 'price_1TXn1T2LoEeIEPVE2YULkFsI',
        amount: 2900, // £29.00
        currency: 'gbp',
        type: 'one_time',
      },
    },
    broskiTokensAwarded: 200,
    modulesUnlocked: [1, 2, 3, 4],
    tier: 'starter',
  },

  builder: {
    productId: 'prod_UWqiuUe1RU9VKL',
    name: '🔥 Builder — Hyper Vibe Coding Course',
    description: 'Modules 1–11 — Full Stack, Agents, AI Pets, Web3, Security, Ship',
    prices: {
      oneTime: {
        priceId: 'price_1TXn1Z2LoEeIEPVEHSj3TDBF',
        amount: 7900, // £79.00
        currency: 'gbp',
        type: 'one_time',
      },
      monthly: {
        priceId: 'price_1TXn1e2LoEeIEPVE00MmiaYj',
        amount: 900, // £9.00/month
        currency: 'gbp',
        type: 'recurring',
        interval: 'month',
      },
    },
    broskiTokensAwarded: 800,
    modulesUnlocked: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    tier: 'builder',
  },

  hyperLegend: {
    productId: 'prod_UWqidgFnOz2QMW',
    name: '⚛️ Hyper Legend — Hyper Vibe Coding Course',
    description: 'Modules 1–13 + Quantum Vibe — The full empire',
    prices: {
      oneTime: {
        priceId: 'price_1TXn1j2LoEeIEPVEjzzhcJny',
        amount: 14900, // £149.00
        currency: 'gbp',
        type: 'one_time',
      },
      monthly: {
        priceId: 'price_1TXn1o2LoEeIEPVEWICzEMHV',
        amount: 1500, // £15.00/month
        currency: 'gbp',
        type: 'recurring',
        interval: 'month',
      },
    },
    broskiTokensAwarded: 2500,
    modulesUnlocked: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    tier: 'hyper_legend',
  },
} as const;

// Price ID → tier lookup (used by the Supabase webhook)
export const PRICE_TO_TIER: Record<string, { tier: string; tokens: number; modules: number[] }> = {
  'price_1TXn1T2LoEeIEPVE2YULkFsI': { tier: 'starter',       tokens: 200,  modules: [1,2,3,4] },
  'price_1TXn1Z2LoEeIEPVEHSj3TDBF': { tier: 'builder',       tokens: 800,  modules: [1,2,3,4,5,6,7,8,9,10,11] },
  'price_1TXn1e2LoEeIEPVE00MmiaYj': { tier: 'builder',       tokens: 800,  modules: [1,2,3,4,5,6,7,8,9,10,11] },
  'price_1TXn1j2LoEeIEPVEjzzhcJny': { tier: 'hyper_legend',  tokens: 2500, modules: [1,2,3,4,5,6,7,8,9,10,11,12,13] },
  'price_1TXn1o2LoEeIEPVEWICzEMHV': { tier: 'hyper_legend',  tokens: 2500, modules: [1,2,3,4,5,6,7,8,9,10,11,12,13] },
};
